//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABC.Core.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM
    {
        public decimal ID { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public Nullable<System.DateTime> YEAR { get; set; }
        public string ORIGIN { get; set; }
        public string CONDITION { get; set; }
    }
}
